// apps/desktop-legacy/src/components/terminal/TerminalPane.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavStore } from "@/stores/navStore";
import { useSessionStore } from "@/stores/sessionStore";
import { useTerminalLayoutStore } from "@/stores/terminalLayoutStore";
import { SplitPaneBar } from "@/components/terminal/SplitPaneBar";
import { SshConnectScreen } from "@/components/terminal/SshConnectScreen";
import { XtermTerminal } from "@/components/terminal/XtermTerminal";

export function TerminalPane() {
  const { t } = useTranslation("terminal");
  const allSessions = useSessionStore((s) => s.sessions);
  const sessions = allSessions.filter((s) => s.kind !== "remote");
  const activeSessionId = useSessionStore((s) => s.activeSessionId);
  const splitMode = useTerminalLayoutStore((s) => s.splitMode);
  const secondarySessionId = useTerminalLayoutStore((s) => s.secondarySessionId);
  const setSecondarySessionId = useTerminalLayoutStore((s) => s.setSecondarySessionId);
  const [mountedTerminalIds, setMountedTerminalIds] = useState<Set<string>>(() => new Set());

  useEffect(() => {
    if (!activeSessionId) return;
    setMountedTerminalIds((prev) => {
      if (prev.has(activeSessionId)) return prev;
      const next = new Set(prev);
      next.add(activeSessionId);
      return next;
    });
  }, [activeSessionId]);

  useEffect(() => {
    if (splitMode === "off" || !activeSessionId) return;
    const valid =
      secondarySessionId &&
      secondarySessionId !== activeSessionId &&
      sessions.some((s) => s.id === secondarySessionId);
    if (valid) return;
    const pick = sessions.find((s) => s.kind !== "remote" && s.id !== activeSessionId)?.id ?? null;
    if (pick !== secondarySessionId) {
      setSecondarySessionId(pick);
    }
  }, [splitMode, activeSessionId, secondarySessionId, sessions, setSecondarySessionId]);

  useEffect(() => {
    if (splitMode === "off") return;
    if (!secondarySessionId) return;
    setMountedTerminalIds((prev) => {
      if (prev.has(secondarySessionId)) return prev;
      const next = new Set(prev);
      next.add(secondarySessionId);
      return next;
    });
  }, [splitMode, secondarySessionId]);

  useEffect(() => {
    setMountedTerminalIds((prev) => {
      let changed = false;
      const next = new Set(prev);
      for (const s of allSessions) {
        if (s.kind === "remote") continue;
        const shouldMount =
          s.kind === "local" ||
          s.sshPhase === "ready" ||
          s.sshPhase === "connecting" ||
          s.sshPhase === "failed";
        if (shouldMount && !next.has(s.id)) {
          next.add(s.id);
          changed = true;
        }
      }
      return changed ? next : prev;
    });
  }, [allSessions]);

  const openTerminal = () => {
    useSessionStore.getState().openLocalShell();
    useNavStore.getState().setView("terminal");
  };

  if (sessions.length === 0) {
    return (
      <div className="terminal terminal--idle">
        <p className="terminal__hint">{t("idle.hint")}</p>
        <button type="button" className="btn btn--primary" onClick={openTerminal}>
          {t("idle.openTerminal")}
        </button>
      </div>
    );
  }

  const splitEnabled =
    splitMode !== "off" &&
    Boolean(activeSessionId) &&
    Boolean(secondarySessionId) &&
    secondarySessionId !== activeSessionId;

  const primary = sessions.find((s) => s.id === activeSessionId) ?? null;
  const secondary = sessions.find((s) => s.id === secondarySessionId) ?? null;
  const secondaryOptions = sessions.filter((s) => s.kind !== "remote" && s.id !== activeSessionId);

  const onSecondaryPick = (id: string) => {
    setSecondarySessionId(id);
    setMountedTerminalIds((prev) => {
      if (prev.has(id)) return prev;
      const next = new Set(prev);
      next.add(id);
      return next;
    });
  };

  const renderSession = (sessionId: string, focusOnActive: boolean) => {
    const session = sessions.find((s) => s.id === sessionId);
    if (!session) return null;
    const active = true;
    const sshConnecting = session.kind === "ssh" && session.sshPhase === "connecting";
    const sshReady = session.kind === "ssh" && session.sshPhase === "ready";
    const sshFailed = session.kind === "ssh" && session.sshPhase === "failed";

    if (!mountedTerminalIds.has(session.id)) return null;

    if (session.kind === "ssh" && (sshConnecting || sshReady)) {
      return (
        <div key={session.id} className="terminal-session terminal-session--active">
          <XtermTerminal
            sessionId={session.id}
            kind={session.kind}
            hostId={session.hostId}
            active={active}
            focusOnActive={focusOnActive}
            listenOnly={sshConnecting}
            backendReady={sshReady}
          />
          {sshConnecting && (
            <SshConnectScreen session={session} active={active} />
          )}
        </div>
      );
    }

    if (sshFailed) {
      return (
        <div key={session.id} className="terminal-session terminal-session--active">
          <SshConnectScreen session={session} active={active} />
        </div>
      );
    }

    if (session.kind === "ssh") return null;

    return (
      <XtermTerminal
        key={session.id}
        sessionId={session.id}
        kind={session.kind}
        hostId={session.hostId}
        active={active}
        focusOnActive={focusOnActive}
      />
    );
  };

  if (splitEnabled && primary && secondary) {
    return (
      <div className={`terminal terminal-split terminal-split--${splitMode}`}>
        <div className="terminal-split__pane">
          <SplitPaneBar role="primary" session={primary} />
          <div className="terminal-split__body">{renderSession(primary.id, true)}</div>
        </div>
        <div className="terminal-split__divider" aria-hidden />
        <div className="terminal-split__pane">
          <SplitPaneBar
            role="secondary"
            session={secondary}
            secondaryOptions={secondaryOptions}
            secondarySessionId={secondarySessionId}
            onSecondaryChange={onSecondaryPick}
          />
          <div className="terminal-split__body">{renderSession(secondary.id, false)}</div>
        </div>
      </div>
    );
  }

  return (
    <div className="terminal">
      {sessions.map((session) => {
        if (session.kind === "remote") return null;
        const active = session.id === activeSessionId;
        const sshConnecting = session.kind === "ssh" && session.sshPhase === "connecting";
        const sshReady = session.kind === "ssh" && session.sshPhase === "ready";
        const sshFailed = session.kind === "ssh" && session.sshPhase === "failed";

        if (!mountedTerminalIds.has(session.id)) {
          return null;
        }

        if (session.kind === "ssh" && (sshConnecting || sshReady)) {
          return (
            <div
              key={session.id}
              className={`terminal-session ${active ? "terminal-session--active" : ""}`}
            >
              <XtermTerminal
                sessionId={session.id}
                kind={session.kind}
                hostId={session.hostId}
                active={active}
                listenOnly={sshConnecting}
                backendReady={sshReady}
              />
              {sshConnecting && active && (
                <SshConnectScreen session={session} active={active} />
              )}
            </div>
          );
        }

        if (sshFailed) {
          return (
            <div
              key={session.id}
              className={`terminal-session ${active ? "terminal-session--active" : ""}`}
            >
              <SshConnectScreen session={session} active={active} />
            </div>
          );
        }

        if (session.kind === "ssh") {
          return null;
        }

        return (
          <XtermTerminal
            key={session.id}
            sessionId={session.id}
            kind={session.kind}
            hostId={session.hostId}
            active={active}
          />
        );
      })}
    </div>
  );
}

// libs/terminal/src/terminal-pane.component.ts
import { AsyncPipe } from "@angular/common";
import { Component, DestroyRef, inject, OnInit, signal } from "@angular/core";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { TranslateModule } from "@ngx-translate/core";
import type { Session } from "@termsh/common";
import { RemoteExplorerPaneComponent } from "@termsh/ssh";
import {
  NavStateService,
  SessionStateService,
  TerminalLayoutStateService,
  type SplitMode,
} from "@termsh/state";
import { combineLatest, map } from "rxjs";
import { SplitPaneBarComponent } from "./split-pane-bar.component";
import { SshConnectScreenComponent } from "./ssh-connect-screen.component";
import { XtermTerminalComponent } from "./xterm-terminal.component";

type SplitVm = {
  splitMode: SplitMode;
  secondaryId: string | null;
  splitEnabled: boolean;
  primary: Session | null;
  secondary: Session | null;
  secondaryOptions: Session[];
  activeId: string | null;
};

@Component({
  selector: "termsh-terminal-pane",
  standalone: true,
  imports: [
    AsyncPipe,
    TranslateModule,
    RemoteExplorerPaneComponent,
    SshConnectScreenComponent,
    XtermTerminalComponent,
    SplitPaneBarComponent,
  ],
  template: `
    @if ((activeRemote$ | async); as remote) {
      <div class="terminal terminal--remote">
        <termsh-remote-explorer-pane [session]="remote" [active]="true" />
      </div>
    } @else {
      @if ((terminalSessions$ | async); as sessions) {
        @if (sessions.length === 0) {
          <div class="terminal terminal--idle">
            <p class="terminal__hint">{{ 'terminal.idle.hint' | translate }}</p>
            <button type="button" class="btn btn--primary" (click)="openTerminal()">
              {{ 'terminal.idle.openTerminal' | translate }}
            </button>
          </div>
        } @else {
          @if (splitVm$ | async; as vm) {
            @if (vm.splitEnabled && vm.primary && vm.secondary) {
              <div class="terminal terminal-split terminal-split--{{ vm.splitMode }}">
            <div class="terminal-split__pane">
              <termsh-split-pane-bar role="primary" [session]="vm.primary" />
              <div class="terminal-split__body">
                @if (vm.primary.kind === 'ssh' && vm.primary.sshPhase !== 'ready') {
                  <termsh-ssh-connect-screen [session]="vm.primary" [active]="true" />
                } @else {
                  <termsh-xterm-terminal
                    [sessionId]="vm.primary.id"
                    [kind]="vm.primary.kind"
                    [hostId]="vm.primary.hostId"
                    [active]="true"
                    [focusOnActive]="true"
                    [sshAlreadyStarted]="vm.primary.kind === 'ssh'"
                  />
                }
              </div>
            </div>
            <div class="terminal-split__divider" aria-hidden="true"></div>
            <div class="terminal-split__pane">
              <termsh-split-pane-bar
                role="secondary"
                [session]="vm.secondary"
                [secondaryOptions]="vm.secondaryOptions"
                [secondarySessionId]="vm.secondaryId"
                (secondaryChange)="onSecondaryPick($event)"
              />
              <div class="terminal-split__body">
                @if (vm.secondary.kind === 'ssh' && vm.secondary.sshPhase !== 'ready') {
                  <termsh-ssh-connect-screen [session]="vm.secondary" [active]="true" />
                } @else {
                  <termsh-xterm-terminal
                    [sessionId]="vm.secondary.id"
                    [kind]="vm.secondary.kind"
                    [hostId]="vm.secondary.hostId"
                    [active]="true"
                    [focusOnActive]="false"
                    [sshAlreadyStarted]="vm.secondary.kind === 'ssh'"
                  />
                }
              </div>
            </div>
          </div>
            } @else {
              <div class="terminal">
                @for (session of sessions; track session.id) {
                  @if (mountedIds().has(session.id)) {
                    @if (session.kind === 'ssh' && session.sshPhase !== 'ready') {
                      <termsh-ssh-connect-screen
                        [session]="session"
                        [active]="vm.activeId === session.id"
                      />
                    } @else {
                      <termsh-xterm-terminal
                        [sessionId]="session.id"
                        [kind]="session.kind"
                        [hostId]="session.hostId"
                        [active]="vm.activeId === session.id"
                        [focusOnActive]="true"
                        [sshAlreadyStarted]="session.kind === 'ssh'"
                      />
                    }
                  }
                }
              </div>
            }
          }
        }
      }
    }
  `,
})
export class TerminalPaneComponent implements OnInit {
  private readonly sessions = inject(SessionStateService);
  private readonly nav = inject(NavStateService);
  private readonly layout = inject(TerminalLayoutStateService);
  private readonly destroyRef = inject(DestroyRef);

  readonly mountedIds = signal(new Set<string>());

  readonly terminalSessions$ = this.sessions.sessionsStream$.pipe(
    map((list) => list.filter((s) => s.kind !== "remote")),
  );

  readonly activeId$ = this.sessions.activeSessionIdStream$;

  readonly activeRemote$ = combineLatest([
    this.sessions.sessionsStream$,
    this.sessions.activeSessionIdStream$,
  ]).pipe(
    map(([list, id]) => {
      const active = list.find((s) => s.id === id);
      return active?.kind === "remote" ? active : null;
    }),
  );

  readonly splitVm$ = combineLatest([
    this.terminalSessions$,
    this.sessions.activeSessionIdStream$,
    this.layout.splitModeStream$,
    this.layout.secondarySessionIdStream$,
  ]).pipe(
    map(([terminalSessions, activeId, splitMode, secondaryId]): SplitVm => {
      const primary = terminalSessions.find((s) => s.id === activeId) ?? null;
      const validSecondary =
        secondaryId &&
        secondaryId !== activeId &&
        terminalSessions.some((s) => s.id === secondaryId);
      const resolvedSecondaryId = validSecondary
        ? secondaryId
        : (terminalSessions.find((s) => s.id !== activeId)?.id ?? null);

      const secondary =
        terminalSessions.find((s) => s.id === resolvedSecondaryId) ?? null;
      const secondaryOptions = terminalSessions.filter((s) => s.id !== activeId);
      const splitEnabled =
        splitMode !== "off" &&
        Boolean(activeId) &&
        Boolean(resolvedSecondaryId) &&
        resolvedSecondaryId !== activeId;

      return {
        splitMode,
        secondaryId: resolvedSecondaryId,
        splitEnabled,
        primary,
        secondary,
        secondaryOptions,
        activeId,
      };
    }),
  );

  ngOnInit() {
    combineLatest([this.sessions.sessionsStream$, this.sessions.activeSessionIdStream$])
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(([allSessions, activeId]) => {
        this.syncMountedIds(allSessions, activeId);
      });

    combineLatest([
      this.terminalSessions$,
      this.sessions.activeSessionIdStream$,
      this.layout.splitModeStream$,
      this.layout.secondarySessionIdStream$,
    ])
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(([terminalSessions, activeId, splitMode, secondaryId]) => {
        if (splitMode === "off" || !activeId) return;
        const valid =
          secondaryId &&
          secondaryId !== activeId &&
          terminalSessions.some((s) => s.id === secondaryId);
        if (valid) return;
        const pick = terminalSessions.find((s) => s.id !== activeId)?.id ?? null;
        if (pick !== secondaryId) {
          this.layout.setSecondarySessionId(pick);
        }
      });

    combineLatest([this.layout.splitModeStream$, this.layout.secondarySessionIdStream$])
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(([splitMode, secondaryId]) => {
        if (splitMode !== "off" && secondaryId) {
          this.addMounted(secondaryId);
        }
      });
  }

  onSecondaryPick(id: string) {
    if (!id) return;
    this.layout.setSecondarySessionId(id);
    this.addMounted(id);
  }

  openTerminal() {
    this.sessions.openLocalShell();
    this.nav.setView("terminal");
  }

  private addMounted(id: string) {
    const next = new Set(this.mountedIds());
    if (next.has(id)) return;
    next.add(id);
    this.mountedIds.set(next);
  }

  private syncMountedIds(allSessions: Session[], activeId: string | null) {
    const next = new Set(this.mountedIds());
    let changed = false;

    if (activeId && !next.has(activeId)) {
      next.add(activeId);
      changed = true;
    }

    for (const session of allSessions) {
      if (session.kind === "remote") continue;
      const shouldMount =
        session.kind === "local" ||
        session.sshPhase === "ready" ||
        session.sshPhase === "connecting" ||
        session.sshPhase === "failed";
      if (shouldMount && !next.has(session.id)) {
        next.add(session.id);
        changed = true;
      }
    }

    for (const id of [...next]) {
      if (!allSessions.some((s) => s.id === id)) {
        next.delete(id);
        changed = true;
      }
    }

    if (changed) {
      this.mountedIds.set(next);
    }
  }
}
