// libs/ssh/src/settings-view.component.ts
import { AsyncPipe } from "@angular/common";
import { Component, inject, OnInit } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { TranslateModule, TranslateService } from "@ngx-translate/core";
import {
  SSH_IDLE_TIMEOUT_VALUES,
  THEME_IDS,
  type SshIdleTimeoutMinutes,
  type ThemeId,
} from "@termsh/common";
import { TermshPlatformService } from "@termsh/platform";
import {
  SettingsStateService,
  SyncStateService,
  UpdaterStateService,
  type AppLocale,
} from "@termsh/state";

@Component({
  selector: "termsh-settings-view",
  standalone: true,
  imports: [AsyncPipe, FormsModule, TranslateModule],
  template: `
    <div class="view">
      <header class="view__head">
        <h1>{{ 'settings.title' | translate }}</h1>
      </header>
      <div class="view__scroll mac-scrollbar settings-form">
        <section class="settings-section">
          <h2 class="settings-section__title">{{ 'settings.language.title' | translate }}</h2>
          <p class="settings-section__desc">{{ 'settings.language.desc' | translate }}</p>
          <div class="settings-field">
            <label class="settings-field__label" for="locale">{{ 'settings.language.label' | translate }}</label>
            <select
              id="locale"
              class="settings-field__select"
              [ngModel]="settings.snapshot.locale"
              (ngModelChange)="onLocale($event)"
              name="locale"
            >
              @for (loc of locales; track loc) {
                <option [value]="loc">{{ loc }}</option>
              }
            </select>
          </div>
        </section>

        <section class="settings-section">
          <h2 class="settings-section__title">{{ 'settings.theme.title' | translate }}</h2>
          <p class="settings-section__desc">{{ 'settings.theme.desc' | translate }}</p>
          <div class="settings-field">
            <label class="settings-field__label" for="theme">{{ 'settings.theme.title' | translate }}</label>
            <select
              id="theme"
              class="settings-field__select"
              [ngModel]="settings.snapshot.themeId"
              (ngModelChange)="onTheme($event)"
              name="theme"
            >
              @for (theme of themeIds; track theme) {
                <option [value]="theme">{{ ('settings.theme.names.' + theme) | translate }}</option>
              }
            </select>
          </div>
        </section>

        <section class="settings-section">
          <h2 class="settings-section__title">{{ 'settings.terminal.title' | translate }}</h2>
          <div class="settings-field">
            <label class="settings-field__label" for="fontSize">{{ 'settings.terminal.sizeLabel' | translate }}</label>
            <input
              id="fontSize"
              class="settings-field__input"
              type="number"
              min="11"
              max="18"
              [ngModel]="settings.snapshot.terminalFontSize"
              (ngModelChange)="onFontSize($event)"
              name="fontSize"
            />
          </div>
        </section>

        <section class="settings-section">
          <h2 class="settings-section__title">{{ 'settings.security.title' | translate }}</h2>
          <p class="settings-section__desc">{{ 'settings.security.desc' | translate }}</p>
          <div class="settings-field">
            <label class="settings-field__label" for="ssh-idle-timeout">{{ 'settings.security.idleLabel' | translate }}</label>
            <select
              id="ssh-idle-timeout"
              class="settings-field__select"
              [ngModel]="settings.snapshot.sshIdleTimeoutMinutes"
              (ngModelChange)="onSshIdle($event)"
              name="sshIdle"
            >
              @for (opt of sshIdleOptions; track opt) {
                <option [value]="opt">{{ ('settings.sshIdle.' + opt) | translate }}</option>
              }
            </select>
          </div>
          <div class="settings-field">
            <label class="settings-field__label" for="vaultAutoLock">{{ 'settings.vaultAutoLock.label' | translate }}</label>
            <select
              id="vaultAutoLock"
              class="settings-field__select"
              [ngModel]="settings.snapshot.vaultAutoLockMinutes"
              (ngModelChange)="onVaultAutoLock($event)"
              name="vaultAutoLock"
            >
              @for (opt of vaultAutoLockOptions; track opt) {
                <option [value]="opt">{{ ('settings.vaultAutoLock.' + opt) | translate }}</option>
              }
            </select>
          </div>
        </section>

        <section class="settings-section">
          <h2 class="settings-section__title">{{ 'settings.sync.title' | translate }}</h2>
          <p class="settings-section__desc">{{ 'settings.sync.desc' | translate }}</p>
          <div class="settings-field">
            <label class="settings-field__label" for="sync-url">{{ 'settings.sync.serverUrl' | translate }}</label>
            <input
              id="sync-url"
              class="settings-field__input"
              type="url"
              [ngModel]="sync.snapshot.serverUrl"
              (ngModelChange)="sync.setServerUrl($event)"
              [placeholder]="'settings.sync.serverUrlPlaceholder' | translate"
              name="syncUrl"
            />
          </div>
          <div class="settings-field">
            <label class="settings-field__label" for="sync-token">{{ 'settings.sync.accessToken' | translate }}</label>
            <input
              id="sync-token"
              class="settings-field__input"
              type="password"
              [ngModel]="sync.snapshot.accessToken"
              (ngModelChange)="sync.setAccessToken($event)"
              [placeholder]="'settings.sync.accessTokenPlaceholder' | translate"
              name="syncToken"
            />
          </div>
          @if (sync.statusStream$ | async; as syncStatus) {
            <p
              class="settings-sync-status"
              [class.settings-sync-status--ok]="syncStatus.connected"
            >
              {{
                syncStatus.connected
                  ? ('settings.sync.connectedAs' | translate : { email: syncStatus.email })
                  : ('settings.sync.notConnected' | translate)
              }}
            </p>
          }
          @if (sync.errorStream$ | async; as syncError) {
            <p class="settings-sync-error">{{ formatSyncError(syncError) }}</p>
          }
          <div class="settings-actions">
            <button
              type="button"
              class="btn btn--ghost"
              [disabled]="(sync.syncingStream$ | async) || !sync.snapshot.serverUrl || !sync.snapshot.accessToken"
              (click)="checkSync()"
            >
              {{ 'settings.sync.testConnection' | translate }}
            </button>
            @if ((sync.statusStream$ | async)?.connected) {
              <button type="button" class="btn btn--ghost" [disabled]="sync.syncingStream$ | async" (click)="pullSync()">
                {{ 'settings.sync.pull' | translate }}
              </button>
              <button type="button" class="btn btn--ghost" [disabled]="sync.syncingStream$ | async" (click)="pushSync()">
                {{ 'settings.sync.push' | translate }}
              </button>
            }
          </div>
          <label class="settings-field vault-field--checkbox">
            <input
              type="checkbox"
              [ngModel]="sync.snapshot.enabled"
              (ngModelChange)="onSyncEnabled($event)"
            />
            <span>{{ 'settings.sync.title' | translate }}</span>
          </label>
          <label class="settings-field vault-field--checkbox">
            <input
              type="checkbox"
              [ngModel]="sync.snapshot.autoSync"
              (ngModelChange)="sync.setAutoSync($event)"
            />
            <span>{{ 'settings.sync.autoSync' | translate }}</span>
          </label>
        </section>

        <section class="settings-section">
          <h2 class="settings-section__title">{{ 'settings.updates.title' | translate }}</h2>
          <p class="settings-section__desc">{{ 'settings.updates.desc' | translate }}</p>
          <div class="settings-field">
            <span class="settings-field__label">{{ 'settings.updates.version' | translate }}</span>
            <span class="settings-field__value">{{ appVersion ?? '—' }}</span>
          </div>
          <div class="settings-field">
            <span class="settings-field__label">{{ 'settings.updates.coreEngine' | translate }}</span>
            <span class="settings-field__value">{{ coreVersion ?? '—' }}</span>
          </div>
          @if (updater.lastMessageStream$ | async; as updateMsg) {
            <p class="settings-sync-status">{{ formatUpdateMessage(updateMsg) }}</p>
          }
          @if (updater.updateAvailableStream$ | async) {
            <p class="settings-sync-status settings-sync-status--ok">
              {{ 'settings.updates.updateAvailable' | translate : { version: updater.updateVersion ?? '' } }}
            </p>
          }
          <div class="settings-actions">
            <button
              type="button"
              class="btn btn--ghost"
              [disabled]="(updater.checkingStream$ | async) || (updater.installingStream$ | async)"
              (click)="checkUpdates()"
            >
              {{
                (updater.checkingStream$ | async)
                  ? ('settings.updates.checking' | translate)
                  : ('settings.updates.checkForUpdates' | translate)
              }}
            </button>
            @if (updater.updateAvailable) {
              <button
                type="button"
                class="btn btn--primary"
                [disabled]="updater.installingStream$ | async"
                (click)="installUpdate()"
              >
                {{
                  (updater.installingStream$ | async)
                    ? ('settings.updates.installing' | translate)
                    : ('settings.updates.install' | translate)
                }}
              </button>
            }
          </div>
        </section>
      </div>
    </div>
  `,
})
export class SettingsViewComponent implements OnInit {
  readonly settings = inject(SettingsStateService);
  readonly sync = inject(SyncStateService);
  readonly updater = inject(UpdaterStateService);
  private readonly translate = inject(TranslateService);
  private readonly platform = inject(TermshPlatformService);

  appVersion: string | null = null;
  coreVersion: string | null = null;

  readonly locales: AppLocale[] = ["en", "tr", "de", "es", "zh"];
  readonly themeIds = THEME_IDS;
  readonly vaultAutoLockOptions = [0, 5, 15, 30, 60];
  readonly sshIdleOptions = SSH_IDLE_TIMEOUT_VALUES;

  ngOnInit() {
    document.documentElement.dataset.theme = this.settings.snapshot.themeId;
    if (this.settings.snapshot.cloudSyncEnabled && !this.sync.snapshot.enabled) {
      this.sync.setEnabled(true);
    }
    void this.platform.appInfo.then((info) => {
      this.appVersion = info.version;
    });
    void this.platform.coreVersion.then((version) => {
      this.coreVersion = version;
    });
  }

  onLocale(locale: AppLocale) {
    this.settings.setLocale(locale);
    void this.translate.use(locale);
  }

  onTheme(themeId: ThemeId) {
    this.settings.setThemeId(themeId);
  }

  onFontSize(size: number) {
    this.settings.setTerminalFontSize(Number(size));
  }

  onVaultAutoLock(minutes: number) {
    const value = Number(minutes);
    this.settings.setVaultAutoLockMinutes(value);
    void this.platform.setAutoLockMinutes(value);
  }

  onSshIdle(minutes: number) {
    this.settings.setSshIdleTimeoutMinutes(Number(minutes) as SshIdleTimeoutMinutes);
  }

  onSyncEnabled(enabled: boolean) {
    this.sync.setEnabled(enabled);
    this.settings.setCloudSyncEnabled(enabled);
  }

  checkSync() {
    void this.sync.checkStatus();
  }

  pullSync() {
    void this.sync.pull();
  }

  pushSync() {
    void this.sync.push();
  }

  formatSyncError(message: string): string {
    if (message.startsWith("settings.")) {
      return this.translate.instant(message);
    }
    return message;
  }

  checkUpdates() {
    void this.updater.check({ notify: false });
  }

  installUpdate() {
    void this.updater.install();
  }

  formatUpdateMessage(message: string): string {
    if (message.startsWith("settings.") || message.startsWith("updater.")) {
      return this.translate.instant(message);
    }
    return message;
  }
}

// apps/desktop-legacy/src/components/views/SettingsView.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { fetchAppInfo } from "@/lib/app/ipc";
import { Icon, type IconName } from "@/components/ui/Icon";
import {
  APP_LOCALES,
  LOCALE_LABELS,
  isAppLocale,
  type AppLocale,
} from "@/i18n/locale";
import { SSH_IDLE_TIMEOUT_VALUES, isSshIdleTimeout } from "@/lib/settings/sshIdle";
import { FONT_OPTIONS, FONT_SIZE_OPTIONS } from "@/lib/settings/terminalFont";
import { THEMES } from "@/lib/themes";
import { isTauriRuntime } from "@/lib/env";
import { useNavStore } from "@/stores/navStore";
import { useSettingsStore } from "@/stores/settingsStore";
import { useSyncStore } from "@/stores/syncStore";
import { useThemeStore } from "@/stores/themeStore";
import { checkForUpdatesInteractive } from "@/lib/updater/check";

type Props = {
  onOpenVaultSetup: () => void;
  onVault: () => void;
};

function SectionCard({
  icon,
  title,
  desc,
  children,
}: {
  icon: IconName;
  title: string;
  desc: string;
  children: React.ReactNode;
}) {
  return (
    <section className="settings-card">
      <header className="settings-card__head">
        <span className="settings-card__icon">
          <Icon name={icon} size={18} />
        </span>
        <div>
          <h2 className="settings-card__title">{title}</h2>
          <p className="settings-card__desc">{desc}</p>
        </div>
      </header>
      <div className="settings-card__body">{children}</div>
    </section>
  );
}

export function SettingsView(_props: Props) {
  const { t } = useTranslation("settings");
  const [appVersion, setAppVersion] = useState<string | null>(null);
  const [updateBusy, setUpdateBusy] = useState(false);

  useEffect(() => {
    if (!isTauriRuntime()) return;
    void fetchAppInfo()
      .then((info) => setAppVersion(info.version))
      .catch(() => setAppVersion(null));
  }, []);

  const setView = useNavStore((s) => s.setView);
  const themeId = useThemeStore((s) => s.themeId);
  const setTheme = useThemeStore((s) => s.setTheme);
  const locale = useSettingsStore((s) => s.locale);
  const setLocale = useSettingsStore((s) => s.setLocale);
  const sshIdleTimeoutMinutes = useSettingsStore((s) => s.sshIdleTimeoutMinutes);
  const setSshIdleTimeoutMinutes = useSettingsStore((s) => s.setSshIdleTimeoutMinutes);
  const terminalFontFamily = useSettingsStore((s) => s.terminalFontFamily);
  const setTerminalFontFamily = useSettingsStore((s) => s.setTerminalFontFamily);
  const terminalFontSize = useSettingsStore((s) => s.terminalFontSize);
  const setTerminalFontSize = useSettingsStore((s) => s.setTerminalFontSize);

  const syncServerUrl = useSyncStore((s) => s.serverUrl);
  const setSyncServerUrl = useSyncStore((s) => s.setServerUrl);
  const syncAccessToken = useSyncStore((s) => s.accessToken);
  const setSyncAccessToken = useSyncStore((s) => s.setAccessToken);
  const syncStatus = useSyncStore((s) => s.status);
  const syncError = useSyncStore((s) => s.error);
  const syncSyncing = useSyncStore((s) => s.syncing);
  const checkSyncStatus = useSyncStore((s) => s.checkStatus);
  const triggerPull = useSyncStore((s) => s.triggerPull);
  const triggerPush = useSyncStore((s) => s.triggerPush);
  const autoSync = useSyncStore((s) => s.autoSync);
  const setAutoSync = useSyncStore((s) => s.setAutoSync);

  const onIdleChange = (value: string) => {
    const minutes = Number(value);
    if (isSshIdleTimeout(minutes)) setSshIdleTimeoutMinutes(minutes);
  };

  const onLocaleChange = (value: string) => {
    if (isAppLocale(value)) setLocale(value);
  };

  return (
    <div className="settings-screen">
      <div className="settings-screen__scroll mac-scrollbar">
        <div className="settings-screen__inner">
          <header className="settings-screen__hero">
            <button type="button" className="settings-screen__back" onClick={() => setView("hosts")}>
              <Icon name="chevron_right" size={14} className="settings-screen__back-icon" />
              <span>{t("backToServers")}</span>
            </button>
            <h1 className="settings-screen__title">{t("title")}</h1>
          </header>

          <SectionCard icon="settings" title={t("language.title")} desc={t("language.desc")}>
            <div className="settings-field">
              <label className="settings-field__label" htmlFor="app-locale">
                {t("language.label")}
              </label>
              <select
                id="app-locale"
                className="settings-field__select"
                value={locale}
                onChange={(e) => onLocaleChange(e.target.value)}
              >
                {APP_LOCALES.map((code) => (
                  <option key={code} value={code}>
                    {LOCALE_LABELS[code as AppLocale]}
                  </option>
                ))}
              </select>
            </div>
          </SectionCard>

          <SectionCard icon="dns" title={t("theme.title")} desc={t("theme.desc")}>
            <div className="settings-theme-grid" role="list">
              {THEMES.map((theme) => {
                const active = themeId === theme.id;
                return (
                  <button
                    key={theme.id}
                    type="button"
                    role="listitem"
                    className={`settings-theme-chip ${active ? "settings-theme-chip--active" : ""}`}
                    onClick={() => setTheme(theme.id)}
                    aria-pressed={active}
                  >
                    <span
                      className="settings-theme-chip__dot"
                      style={{ background: theme.swatch }}
                      aria-hidden
                    />
                    <span className="settings-theme-chip__label">
                      {t(`theme.names.${theme.id}`, { defaultValue: theme.label })}
                    </span>
                  </button>
                );
              })}
            </div>
          </SectionCard>

          <SectionCard icon="lock" title={t("security.title")} desc={t("security.desc")}>
            <div className="settings-field">
              <label className="settings-field__label" htmlFor="ssh-idle-timeout">
                {t("security.idleLabel")}
              </label>
              <select
                id="ssh-idle-timeout"
                className="settings-field__select"
                value={sshIdleTimeoutMinutes}
                onChange={(e) => onIdleChange(e.target.value)}
              >
                {SSH_IDLE_TIMEOUT_VALUES.map((value) => (
                  <option key={value} value={value}>
                    {t(`sshIdle.${value}`)}
                  </option>
                ))}
              </select>
            </div>
          </SectionCard>

          <SectionCard icon="terminal" title={t("terminal.title")} desc={t("terminal.desc")}>
            <div className="settings-field">
              <label className="settings-field__label" htmlFor="terminal-font-family">
                {t("terminal.fontLabel")}
              </label>
              <select
                id="terminal-font-family"
                className="settings-field__select"
                value={terminalFontFamily}
                onChange={(e) => setTerminalFontFamily(e.target.value as typeof terminalFontFamily)}
              >
                {FONT_OPTIONS.map((opt) => (
                  <option key={opt.value} value={opt.value}>
                    {opt.label}
                  </option>
                ))}
              </select>
            </div>
            <div className="settings-field">
              <label className="settings-field__label" htmlFor="terminal-font-size">
                {t("terminal.sizeLabel")}
              </label>
              <select
                id="terminal-font-size"
                className="settings-field__select"
                value={terminalFontSize}
                onChange={(e) => setTerminalFontSize(Number(e.target.value))}
              >
                {FONT_SIZE_OPTIONS.map((size) => (
                  <option key={size} value={size}>
                    {t("terminal.sizePx", { size })}
                  </option>
                ))}
              </select>
            </div>
          </SectionCard>

          <SectionCard icon="cloud" title={t("sync.title")} desc={t("sync.desc")}>
            <div className="settings-field">
              <label className="settings-field__label" htmlFor="sync-server-url">
                {t("sync.serverUrl")}
              </label>
              <input
                id="sync-server-url"
                type="url"
                className="settings-field__input"
                value={syncServerUrl}
                onChange={(e) => setSyncServerUrl(e.target.value)}
                placeholder={t("sync.serverUrlPlaceholder")}
              />
            </div>
            <div className="settings-field">
              <label className="settings-field__label" htmlFor="sync-token">
                {t("sync.accessToken")}
              </label>
              <input
                id="sync-token"
                type="password"
                className="settings-field__input"
                value={syncAccessToken}
                onChange={(e) => setSyncAccessToken(e.target.value)}
                placeholder={t("sync.accessTokenPlaceholder")}
              />
            </div>
            {syncStatus && (
              <p className={`settings-sync-status ${syncStatus.connected ? "settings-sync-status--ok" : ""}`}>
                {syncStatus.connected
                  ? t("sync.connectedAs", { email: syncStatus.email })
                  : t("sync.notConnected")}
              </p>
            )}
            {syncError && <p className="settings-sync-error">{syncError}</p>}
            <div className="settings-actions">
              <button
                type="button"
                className="btn btn--secondary"
                disabled={syncSyncing || !syncServerUrl || !syncAccessToken}
                onClick={() => void checkSyncStatus()}
              >
                {t("sync.testConnection")}
              </button>
              {syncStatus?.connected && (
                <>
                  <button
                    type="button"
                    className="btn btn--secondary"
                    disabled={syncSyncing}
                    onClick={() => void triggerPull()}
                  >
                    {t("sync.pull")}
                  </button>
                  <button
                    type="button"
                    className="btn btn--secondary"
                    disabled={syncSyncing}
                    onClick={() => void triggerPush()}
                  >
                    {t("sync.push")}
                  </button>
                </>
              )}
            </div>
            <div className="settings-row">
              <label className="settings-field__label">
                <input type="checkbox" checked={autoSync} onChange={(e) => setAutoSync(e.target.checked)} />
                {" "}
                {t("sync.autoSync")}
              </label>
            </div>
          </SectionCard>

          <SectionCard icon="cloud" title={t("updates.title")} desc={t("updates.desc")}>
            <div className="settings-field">
              <span className="settings-field__label">{t("updates.version")}</span>
              <span className="settings-field__value">{appVersion ?? "—"}</span>
            </div>
            <div className="settings-actions">
              <button
                type="button"
                className="btn btn--secondary"
                disabled={!isTauriRuntime() || updateBusy}
                onClick={() => {
                  setUpdateBusy(true);
                  void checkForUpdatesInteractive().finally(() => setUpdateBusy(false));
                }}
              >
                {updateBusy ? t("updates.checking") : t("updates.checkForUpdates")}
              </button>
            </div>
          </SectionCard>
        </div>
      </div>
    </div>
  );
}
