// libs/vault/src/vault-view.component.ts
import { Component, inject } from "@angular/core";
import { TranslateModule } from "@ngx-translate/core";
import { NavStateService, VaultStateService } from "@termsh/state";
import { biometricLabelKey } from "./biometric";

@Component({
  selector: "termsh-vault-view",
  standalone: true,
  imports: [TranslateModule],
  template: `
    <div class="view view--vault">
      <header class="view__head">
        <h1>{{ 'vault.title' | translate }}</h1>
        <p class="view__sub">{{ 'vault.subtitle' | translate }}</p>
      </header>

      <div class="view__scroll mac-scrollbar">
        <div class="vault-panel">
          <div class="vault-panel__status-row">
            <span
              class="vault-panel__dot"
              [class.vault-panel__dot--ok]="vaultReady"
              [class.vault-panel__dot--off]="!vaultReady"
              aria-hidden="true"
            ></span>
            <span>
              @if (!vault.status?.isSetup) {
                {{ 'vault.status.notSetup' | translate }}
              } @else if (vaultReady) {
                {{ 'vault.status.unlocked' | translate }}
              } @else {
                {{ 'vault.status.locked' | translate }}
              }
            </span>
          </div>

          @if (vault.status?.biometricEnabled && vault.status?.isSetup) {
            <p class="vault-panel__keychain">
              {{
                'vault.biometric.enabled'
                  | translate: { method: (biometricMethodLabel() | translate) }
              }}
            </p>
          }

          @if (
            vault.status?.keychainAvailable &&
            vault.status?.isSetup &&
            !vault.status?.biometricEnabled
          ) {
            <p class="vault-panel__keychain">
              {{
                (vault.status?.keychainEnabled
                  ? 'vault.keychain.enabled'
                  : 'vault.keychain.disabled') | translate
              }}
            </p>
          }

          <div class="vault-panel__actions">
            @if (!vault.status?.isSetup) {
              <button type="button" class="btn btn--primary" (click)="openSetup()">
                {{ 'vault.actions.setup' | translate }}
              </button>
            } @else {
              <button type="button" class="btn btn--primary" (click)="onVaultAction()">
                {{
                  (vaultReady ? 'vault.actions.lock' : 'vault.actions.unlock') | translate
                }}
              </button>
              @if (deviceUnlockEnabled) {
                <button type="button" class="btn btn--secondary" (click)="forgetDeviceUnlock()">
                  {{ 'vault.actions.forgetDeviceUnlock' | translate }}
                </button>
              }
            }
          </div>
        </div>

        <section class="view__section">
          <h2>{{ 'vault.protectsTitle' | translate }}</h2>
          <ul class="vault-feature-list">
            <li>{{ 'vault.protects.passwords' | translate }}</li>
            <li>{{ 'vault.protects.keys' | translate }}</li>
            <li>{{ 'vault.protects.snippets' | translate }}</li>
            <li>{{ 'vault.protects.kdf' | translate }}</li>
          </ul>
        </section>
      </div>
    </div>
  `,
})
export class VaultViewComponent {
  readonly vault = inject(VaultStateService);
  private readonly nav = inject(NavStateService);

  get vaultReady(): boolean {
    const s = this.vault.status;
    return Boolean(s?.isSetup && s.isUnlocked);
  }

  get deviceUnlockEnabled(): boolean {
    const s = this.vault.status;
    return Boolean(s?.biometricEnabled || s?.keychainEnabled);
  }

  biometricMethodLabel() {
    return biometricLabelKey(this.vault.status?.biometricKind ?? "generic");
  }

  openSetup() {
    this.nav.setView("vault");
  }

  onVaultAction() {
    if (this.vaultReady) {
      void this.vault.lock();
      return;
    }
    void this.vault.bootstrap();
  }

  forgetDeviceUnlock() {
    void this.vault.forgetKeychain();
  }
}

// apps/desktop-legacy/src/components/views/VaultView.tsx
import { useTranslation } from "react-i18next";
import { biometricLabelKey } from "@/lib/vault/biometric";
import { useVaultStore } from "@/stores/vaultStore";

type Props = {
  onOpenVaultSetup: () => void;
  onVault: () => void;
};

export function VaultView({ onOpenVaultSetup, onVault }: Props) {
  const { t } = useTranslation("vault");
  const vaultStatus = useVaultStore((s) => s.status);
  const forgetKeychain = useVaultStore((s) => s.forgetKeychain);
  const vaultReady = Boolean(vaultStatus?.isSetup && vaultStatus?.isUnlocked);
  const deviceUnlockEnabled =
    Boolean(vaultStatus?.biometricEnabled) || Boolean(vaultStatus?.keychainEnabled);

  return (
    <div className="view view--vault">
      <header className="view__head">
        <h1>{t("title")}</h1>
        <p className="view__sub">{t("subtitle")}</p>
      </header>

      <div className="view__scroll mac-scrollbar">
        <div className="vault-panel">
          <div className="vault-panel__status-row">
            <span
              className={`vault-panel__dot ${vaultReady ? "vault-panel__dot--ok" : "vault-panel__dot--off"}`}
              aria-hidden
            />
            <span>
              {!vaultStatus?.isSetup
                ? t("status.notSetup")
                : vaultReady
                  ? t("status.unlocked")
                  : t("status.locked")}
            </span>
          </div>

          {vaultStatus?.biometricEnabled && vaultStatus.isSetup && (
            <p className="vault-panel__keychain">
              {t("biometric.enabled", {
                method: t(biometricLabelKey(vaultStatus.biometricKind)),
              })}
            </p>
          )}

          {vaultStatus?.keychainAvailable &&
            vaultStatus.isSetup &&
            !vaultStatus.biometricEnabled && (
              <p className="vault-panel__keychain">
                {vaultStatus.keychainEnabled ? t("keychain.enabled") : t("keychain.disabled")}
              </p>
            )}

          <div className="vault-panel__actions">
            {!vaultStatus?.isSetup ? (
              <button type="button" className="btn btn--primary" onClick={onOpenVaultSetup}>
                {t("actions.setup")}
              </button>
            ) : (
              <>
                <button type="button" className="btn btn--primary" onClick={onVault}>
                  {vaultReady ? t("actions.lock") : t("actions.unlock")}
                </button>
                {deviceUnlockEnabled && (
                  <button
                    type="button"
                    className="btn btn--secondary"
                    onClick={() => void forgetKeychain()}
                  >
                    {t("actions.forgetDeviceUnlock")}
                  </button>
                )}
              </>
            )}
          </div>
        </div>

        <section className="view__section">
          <h2>{t("protectsTitle")}</h2>
          <ul className="vault-feature-list">
            <li>{t("protects.passwords")}</li>
            <li>{t("protects.keys")}</li>
            <li>{t("protects.snippets")}</li>
            <li>{t("protects.kdf")}</li>
          </ul>
        </section>
      </div>
    </div>
  );
}
