// apps/desktop-legacy/src/components/vault/UnlockView.tsx
import { FormEvent, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { TermshLogo } from "@/components/brand/TermshLogo";
import { Icon } from "@/components/ui/Icon";
import { biometricIcon, biometricLabelKey } from "@/lib/vault/biometric";
import { startDraggingMainWindow } from "@/lib/window";
import { useVaultStore } from "@/stores/vaultStore";

export function UnlockView() {
  const { t } = useTranslation("vault");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [useDeviceUnlock, setUseDeviceUnlock] = useState(true);
  const status = useVaultStore((s) => s.status);
  const error = useVaultStore((s) => s.error);
  const unlock = useVaultStore((s) => s.unlock);
  const unlockWithBiometric = useVaultStore((s) => s.unlockWithBiometric);
  const bootstrap = useVaultStore((s) => s.bootstrap);
  const clearError = useVaultStore((s) => s.clearError);
  const keychainAvailable = status?.keychainAvailable ?? false;
  const biometricAvailable = status?.biometricAvailable ?? false;
  const biometricKind = status?.biometricKind ?? "none";
  const autoTried = useRef(false);

  const unlockOptions = () => ({
    useBiometric: biometricAvailable && useDeviceUnlock,
    rememberInKeychain: !biometricAvailable && keychainAvailable && useDeviceUnlock,
  });

  useEffect(() => {
    if (autoTried.current) return;
    if (!status?.biometricEnabled && !status?.keychainEnabled) return;
    autoTried.current = true;
    setSubmitting(true);
    void bootstrap().finally(() => setSubmitting(false));
  }, [bootstrap, status?.biometricEnabled, status?.keychainEnabled]);

  const onBiometricUnlock = async () => {
    clearError();
    setSubmitting(true);
    try {
      await unlockWithBiometric();
    } finally {
      setSubmitting(false);
    }
  };

  const onSubmit = async (event: FormEvent) => {
    event.preventDefault();
    clearError();
    setSubmitting(true);
    try {
      await unlock(password, unlockOptions());
      setPassword("");
    } catch {
      // store handles error
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="vault-unlock">
      <div
        className="vault-unlock__drag"
        data-tauri-drag-region
        onMouseDown={(e) => {
          if (e.button !== 0) return;
          void startDraggingMainWindow();
        }}
        aria-hidden
      />
      <div className="vault-unlock__panel">
        <header className="vault-unlock__hero">
          <div className="vault-unlock__app-icon" aria-hidden>
            <TermshLogo variant="mark" size={30} />
          </div>
          <div className="vault-unlock__hero-text">
            <h1 className="vault-unlock__title">{t("unlock.title")}</h1>
            <p className="vault-unlock__subtitle">{t("unlock.subtitle")}</p>
          </div>
        </header>

        {error && (
          <p className="vault-unlock__error" role="alert">
            {error}
          </p>
        )}

        {status?.biometricEnabled && (
          <button
            type="button"
            className="vault-unlock__biometric"
            onClick={() => void onBiometricUnlock()}
            disabled={submitting}
          >
            <Icon name={biometricIcon(biometricKind)} size={22} />
            <span>{t("unlock.biometricButton", { method: t(biometricLabelKey(biometricKind)) })}</span>
          </button>
        )}

        <form className="vault-unlock__form" onSubmit={onSubmit}>
          <div className="vault-unlock__field">
            <label className="vault-unlock__sr-only" htmlFor="vault-master-password">
              {t("unlock.masterPassword")}
            </label>
            <input
              id="vault-master-password"
              className="vault-unlock__input"
              type={showPassword ? "text" : "password"}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              autoComplete="current-password"
              minLength={8}
              required
              placeholder={t("unlock.placeholder")}
              autoFocus={!status?.biometricEnabled}
            />
            <button
              type="button"
              className="vault-unlock__toggle"
              onClick={() => setShowPassword((v) => !v)}
              aria-label={showPassword ? t("unlock.hidePassword") : t("unlock.showPassword")}
            >
              <Icon name={showPassword ? "visibility_off" : "visibility"} size={18} />
            </button>
          </div>

          {(biometricAvailable || keychainAvailable) && (
            <label className="vault-unlock__remember">
              <input
                type="checkbox"
                checked={useDeviceUnlock}
                onChange={(e) => setUseDeviceUnlock(e.target.checked)}
              />
              <span>
                {biometricAvailable
                  ? t("unlock.useBiometric", { method: t(biometricLabelKey(biometricKind)) })
                  : t("unlock.rememberKeychain")}
              </span>
            </label>
          )}

          <button
            type="submit"
            className="vault-unlock__submit"
            disabled={submitting || password.length < 8}
          >
            {submitting ? t("unlock.unlocking") : t("unlock.unlockButton")}
          </button>
        </form>
      </div>

      <p className="vault-unlock__footnote">{t("unlock.footnote")}</p>
    </div>
  );
}

// libs/vault/src/unlock-view.component.ts
import { Component, effect, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { TranslateModule } from "@ngx-translate/core";
import { TermshIconComponent, TermshLogoComponent } from "@termsh/angular";
import type { VaultUnlockOptions } from "@termsh/platform";
import { VaultStateService } from "@termsh/state";
import { biometricIcon, biometricLabelKey } from "./biometric";
import { SecretInputComponent } from "./secret-input.component";

@Component({
  selector: "termsh-unlock-view",
  standalone: true,
  imports: [
    FormsModule,
    TranslateModule,
    TermshLogoComponent,
    TermshIconComponent,
    SecretInputComponent,
  ],
  template: `
    @if (vault.status?.isSetup) {
      <div class="vault-unlock">
        <div class="vault-unlock__drag" aria-hidden="true"></div>
        <div class="vault-unlock__panel">
          <header class="vault-unlock__hero">
            <div class="vault-unlock__app-icon" aria-hidden="true">
              <termsh-logo variant="mark" [size]="30" />
            </div>
            <div class="vault-unlock__hero-text">
              <h1 class="vault-unlock__title">{{ 'vault.unlock.title' | translate }}</h1>
              <p class="vault-unlock__subtitle">{{ 'vault.unlock.subtitle' | translate }}</p>
            </div>
          </header>

          @if (error()) {
            <p class="vault-unlock__error" role="alert">{{ error() }}</p>
          }

          @if (vault.status?.biometricEnabled) {
            <button
              type="button"
              class="vault-unlock__biometric"
              [disabled]="busy()"
              (click)="onBiometricUnlock()"
            >
              <termsh-icon [name]="biometricIconName()" [size]="22" />
              <span>{{
                'vault.unlock.biometricButton'
                  | translate: { method: (biometricMethodLabel() | translate) }
              }}</span>
            </button>
          }

          <form class="vault-unlock__form" (ngSubmit)="submit()">
            <termsh-secret-input
              variant="unlock"
              [(value)]="password"
              name="password"
              [label]="'vault.unlock.masterPassword' | translate"
              [placeholder]="'vault.unlock.placeholder' | translate"
              autocomplete="current-password"
              [required]="true"
            />

            @if (showDeviceUnlockOption()) {
              <label class="vault-unlock__remember">
                <input
                  type="checkbox"
                  name="useDeviceUnlock"
                  [(ngModel)]="useDeviceUnlock"
                />
                <span>
                  @if (vault.status?.biometricAvailable) {
                    {{
                      'vault.unlock.useBiometric'
                        | translate: { method: (biometricMethodLabel() | translate) }
                    }}
                  } @else {
                    {{ 'vault.unlock.rememberKeychain' | translate }}
                  }
                </span>
              </label>
            }

            <button
              type="submit"
              class="vault-unlock__submit"
              [disabled]="busy() || password.length < 8"
            >
              {{
                (busy() ? 'vault.unlock.unlocking' : 'vault.unlock.unlockButton') | translate
              }}
            </button>
          </form>
        </div>

        <p class="vault-unlock__footnote">{{ 'vault.unlock.footnote' | translate }}</p>
      </div>
    } @else {
      <div class="vault-screen">
        <div class="vault-card">
          <div class="vault-card__brand">
            <termsh-logo variant="wordmark" [size]="32" />
          </div>
          <h1>{{ 'vault.setup.title' | translate }}</h1>
          <p class="vault-card__lead">{{ 'vault.setup.lead' | translate }}</p>
          <form class="vault-form" (ngSubmit)="submit()">
            <termsh-secret-input
              [(value)]="password"
              name="password"
              [label]="'vault.setup.masterPassword' | translate"
              [placeholder]="'vault.unlock.placeholder' | translate"
              autocomplete="new-password"
              [required]="true"
            />

            @if (showDeviceUnlockOption()) {
              <label class="vault-unlock__remember">
                <input
                  type="checkbox"
                  name="useDeviceUnlock"
                  [(ngModel)]="useDeviceUnlock"
                />
                <span>
                  @if (vault.status?.biometricAvailable) {
                    {{
                      'vault.setup.useBiometric'
                        | translate: { method: (biometricMethodLabel() | translate) }
                    }}
                  } @else {
                    {{ 'vault.setup.rememberKeychain' | translate }}
                  }
                </span>
              </label>
            }

            @if (error()) {
              <p class="vault-card__error">{{ error() }}</p>
            }
            <button type="submit" class="btn btn--primary" [disabled]="busy() || password.length < 8">
              {{ 'vault.setup.createButton' | translate }}
            </button>
          </form>
        </div>
      </div>
    }
  `,
})
export class UnlockViewComponent {
  readonly vault = inject(VaultStateService);

  password = "";
  useDeviceUnlock = true;
  readonly busy = signal(false);
  readonly error = signal<string | null>(null);
  private autoTried = false;

  constructor() {
    effect(() => {
      const status = this.vault.status;
      if (this.autoTried || !status) return;
      if (!status.biometricEnabled && !status.keychainEnabled) return;
      this.autoTried = true;
      this.busy.set(true);
      void this.vault.bootstrap().finally(() => this.busy.set(false));
    });
  }

  biometricIconName() {
    return biometricIcon(this.vault.status?.biometricKind ?? "none");
  }

  biometricMethodLabel() {
    return biometricLabelKey(this.vault.status?.biometricKind ?? "generic");
  }

  showDeviceUnlockOption(): boolean {
    const status = this.vault.status;
    if (!status) return false;
    return Boolean(status.biometricAvailable || status.keychainAvailable);
  }

  unlockOptions(): VaultUnlockOptions {
    const status = this.vault.status;
    return {
      useBiometric: Boolean(status?.biometricAvailable && this.useDeviceUnlock),
      rememberInKeychain: Boolean(
        !status?.biometricAvailable && status?.keychainAvailable && this.useDeviceUnlock,
      ),
    };
  }

  async onBiometricUnlock() {
    this.vault.clearError();
    this.error.set(null);
    this.busy.set(true);
    try {
      await this.vault.unlockWithBiometric();
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : String(e));
    } finally {
      this.busy.set(false);
    }
  }

  async submit() {
    if (!this.password || this.busy()) return;
    this.vault.clearError();
    this.error.set(null);
    this.busy.set(true);
    try {
      if (this.vault.status?.isSetup) {
        await this.vault.unlock(this.password, this.unlockOptions());
      } else {
        await this.vault.setup(this.password, this.unlockOptions());
      }
      this.password = "";
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : String(e));
    } finally {
      this.busy.set(false);
    }
  }
}
