// libs/terminal/src/split-pane-bar.component.ts
import { Component, input, output } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { TranslateModule } from "@ngx-translate/core";
import { TermshIconComponent } from "@termsh/angular";
import type { Session } from "@termsh/common";

@Component({
  selector: "termsh-split-pane-bar",
  standalone: true,
  imports: [FormsModule, TranslateModule, TermshIconComponent],
  template: `
    <div
      class="terminal-split__bar"
      role="group"
      [attr.aria-label]="
        role() === 'primary'
          ? ('terminal.split.primaryAria' | translate)
          : ('terminal.split.secondaryAria' | translate)
      "
    >
      <span class="terminal-split__bar-tag">
        {{
          role() === 'primary'
            ? ('terminal.split.primary' | translate)
            : ('terminal.split.split' | translate)
        }}
      </span>

      @if (role() === 'primary') {
        <span class="terminal-split__bar-title">
          @if (session(); as s) {
            <termsh-icon [name]="sessionIcon(s)" [size]="12" />
            <span>{{ s.title }}</span>
          } @else {
            —
          }
        </span>
      } @else {
        <label class="terminal-split__bar-select-wrap">
          <select
            class="terminal-split__bar-select"
            [attr.aria-label]="'terminal.split.secondarySession' | translate"
            [ngModel]="secondarySessionId() ?? ''"
            (ngModelChange)="secondaryChange.emit($event)"
            [disabled]="secondaryOptions().length === 0"
          >
            @if (secondaryOptions().length === 0) {
              <option value="">{{ 'terminal.split.noOtherSession' | translate }}</option>
            }
            @for (s of secondaryOptions(); track s.id) {
              <option [value]="s.id">
                {{
                  s.kind === 'local'
                    ? ('terminal.split.local' | translate)
                    : s.title
                }}
              </option>
            }
          </select>
        </label>
      }
    </div>
  `,
})
export class SplitPaneBarComponent {
  readonly role = input.required<"primary" | "secondary">();
  readonly session = input<Session | null>(null);
  readonly secondaryOptions = input<Session[]>([]);
  readonly secondarySessionId = input<string | null>(null);

  readonly secondaryChange = output<string>();

  sessionIcon(session: Session): "laptop" | "terminal" {
    return session.kind === "local" ? "laptop" : "terminal";
  }
}

// apps/desktop-legacy/src/components/terminal/SplitPaneBar.tsx
import { useTranslation } from "react-i18next";
import type { Session } from "@termsh/shared";
import { Icon } from "@/components/ui/Icon";

type Props = {
  role: "primary" | "secondary";
  session: Session | null;
  secondaryOptions?: Session[];
  secondarySessionId?: string | null;
  onSecondaryChange?: (id: string) => void;
};

export function SplitPaneBar({
  role,
  session,
  secondaryOptions = [],
  secondarySessionId,
  onSecondaryChange,
}: Props) {
  const { t } = useTranslation("terminal");
  const icon = session?.kind === "local" ? "laptop" : "terminal";

  return (
    <div
      className="terminal-split__bar"
      role="group"
      aria-label={role === "primary" ? t("split.primaryAria") : t("split.secondaryAria")}
    >
      <span className="terminal-split__bar-tag">
        {role === "primary" ? t("split.primary") : t("split.split")}
      </span>

      {role === "primary" ? (
        <span className="terminal-split__bar-title">
          {session ? (
            <>
              <Icon name={icon} size={12} />
              <span>{session.title}</span>
            </>
          ) : (
            "—"
          )}
        </span>
      ) : (
        <label className="terminal-split__bar-select-wrap">
          <select
            className="terminal-split__bar-select"
            aria-label={t("split.secondarySession")}
            value={secondarySessionId ?? ""}
            onChange={(e) => onSecondaryChange?.(e.target.value)}
            disabled={secondaryOptions.length === 0}
          >
            {secondaryOptions.length === 0 && (
              <option value="">{t("split.noOtherSession")}</option>
            )}
            {secondaryOptions.map((s) => (
              <option key={s.id} value={s.id}>
                {s.kind === "local" ? t("split.local") : s.title}
              </option>
            ))}
          </select>
        </label>
      )}
    </div>
  );
}
