// libs/terminal/src/xterm-terminal.component.ts
import {
  AfterViewInit,
  Component,
  DestroyRef,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  inject,
  viewChild,
} from "@angular/core";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { FitAddon } from "@xterm/addon-fit";
import { Terminal } from "@xterm/xterm";
import type { SessionKind } from "@termsh/common";
import { TermshPlatformService } from "@termsh/platform";
import {
  ActivityTrackerService,
  SessionStateService,
  SettingsStateService,
  touchSessionActivity,
} from "@termsh/state";
import { getXtermTheme } from "./xterm-theme";

const RESIZE_DEBOUNCE_MS = 80;

@Component({
  selector: "termsh-xterm-terminal",
  standalone: true,
  template: `<div class="xterm-host" [class.xterm-host--active]="active" #host></div>`,
})
export class XtermTerminalComponent implements AfterViewInit, OnChanges, OnDestroy {
  private readonly platform = inject(TermshPlatformService);
  private readonly sessions = inject(SessionStateService);
  private readonly activity = inject(ActivityTrackerService);

  @Input({ required: true }) sessionId!: string;
  @Input({ required: true }) kind!: SessionKind;
  @Input() hostId?: string;
  @Input() active = false;
  /** Focus xterm when this pane becomes the active tab. */
  @Input() focusOnActive = true;
  /** SSH PTY was started by SshConnectScreen — attach only, do not respawn. */
  @Input() sshAlreadyStarted = false;

  private readonly hostRef = viewChild.required<ElementRef<HTMLDivElement>>("host");
  private readonly settings = inject(SettingsStateService);
  private readonly destroyRef = inject(DestroyRef);

  private term: Terminal | null = null;
  private fit: FitAddon | null = null;
  private spawned = false;
  private resizeTimer: ReturnType<typeof setTimeout> | null = null;
  private resizeObserver: ResizeObserver | null = null;
  private unsubData: (() => void) | null = null;
  private unsubExit: (() => void) | null = null;
  private dataDisposable: { dispose(): void } | null = null;

  ngOnChanges(changes: SimpleChanges) {
    if (changes["active"] && this.active && this.focusOnActive) {
      this.term?.focus();
    }
  }

  ngAfterViewInit() {
    const container = this.hostRef().nativeElement;
    const fontSize = this.settings.snapshot.terminalFontSize;
    const term = new Terminal({
      cursorBlink: true,
      fontSize,
      fontFamily: '"JetBrains Mono", "SF Mono", ui-monospace, Menlo, monospace',
      theme: getXtermTheme(this.settings.snapshot.themeId),
      smoothScrollDuration: 0,
    });
    const fitAddon = new FitAddon();
    term.loadAddon(fitAddon);
    term.open(container);
    fitAddon.fit();

    this.term = term;
    this.fit = fitAddon;

    this.dataDisposable = term.onData((data) => {
      this.activity.ping();
      if (this.kind === "ssh") {
        touchSessionActivity(this.sessionId);
      }
      if (this.spawned) {
        this.platform.ptyWrite(this.sessionId, data);
      }
    });

    this.unsubData = this.platform.onPtyData(({ sessionId, data }) => {
      if (sessionId !== this.sessionId || !this.term) return;
      if (this.kind === "ssh") {
        touchSessionActivity(sessionId);
      }
      this.term.write(data);
    });

    this.unsubExit = this.platform.onPtyExit(({ sessionId }) => {
      if (sessionId !== this.sessionId || !this.term) return;
      this.term.writeln("\r\n\x1b[90m[session ended]\x1b[0m");
      if (this.kind === "ssh") {
        this.sessions.markSshFailed(sessionId, "Connection closed");
      }
      void this.sessions.closeSession(sessionId);
    });

    void this.startShell();

    this.resizeObserver = new ResizeObserver(() => this.scheduleFitAndResize());
    this.resizeObserver.observe(container);

    this.settings.snapshotStream$
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((snap) => {
        term.options.theme = getXtermTheme(snap.themeId);
        term.options.fontSize = snap.terminalFontSize;
        this.scheduleFitAndResize();
      });
  }

  ngOnDestroy() {
    if (this.resizeTimer) clearTimeout(this.resizeTimer);
    this.dataDisposable?.dispose();
    this.unsubData?.();
    this.unsubExit?.();
    this.resizeObserver?.disconnect();
    this.term?.dispose();
    this.term = null;
    this.fit = null;
    this.spawned = false;
  }

  private scheduleFitAndResize() {
    if (this.resizeTimer) clearTimeout(this.resizeTimer);
    this.resizeTimer = setTimeout(() => {
      this.resizeTimer = null;
      const term = this.term;
      const fit = this.fit;
      if (!term || !fit) return;
      fit.fit();
      if (this.spawned) {
        this.platform.ptyResize(this.sessionId, term.cols, term.rows);
      }
    }, RESIZE_DEBOUNCE_MS);
  }

  private async startShell() {
    if (this.spawned) return;

    const term = this.term;
    const fit = this.fit;
    if (!term || !fit) return;

    fit.fit();
    try {
      if (this.kind === "ssh") {
        if (!this.sshAlreadyStarted) {
          if (!this.hostId) throw new Error("Missing host id");
          await this.platform.spawnSshShell(this.sessionId, this.hostId, term.cols, term.rows);
          this.sessions.markSshReady(this.sessionId);
        }
      } else {
        await this.platform.spawnLocalShell(this.sessionId, term.cols, term.rows);
      }
      this.spawned = true;
      term.focus();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (this.kind === "ssh") {
        this.sessions.markSshFailed(this.sessionId, msg);
      }
      term.writeln(`\r\n\x1b[31mFailed to start shell:\x1b[0m ${msg}`);
    }
  }
}

// apps/desktop-legacy/src/components/terminal/XtermTerminal.tsx
import { FitAddon } from "@xterm/addon-fit";
import { Terminal } from "@xterm/xterm";
import { listen } from "@tauri-apps/api/event";
import { useCallback, useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import type { SessionKind } from "@termsh/shared";
import { getTheme } from "@/lib/themes";
import { buildFontFamilyCss } from "@/lib/settings/terminalFont";
import { formatAppError, translateTerminalChunk } from "@/lib/errors/appError";
import {
  decodeTerminalData,
  spawnLocalShell,
  spawnSshShell,
  terminalResize,
  terminalWrite,
} from "@/lib/terminal/ipc";
import { touchSessionActivity } from "@/lib/session/activity";
import { useNavStore } from "@/stores/navStore";
import { useSessionStore } from "@/stores/sessionStore";
import { useSettingsStore } from "@/stores/settingsStore";
import { useTerminalStreamStore } from "@/stores/terminalStreamStore";
import { useThemeStore } from "@/stores/themeStore";
import "@xterm/xterm/css/xterm.css";

type TerminalExitEvent = {
  sessionId: string;
};

type Props = {
  sessionId: string;
  kind: SessionKind;
  hostId?: string;
  active: boolean;
  focusOnActive?: boolean;
  /** SSH zaten SshConnectScreen üzerinden başlatıldıysa true */
  backendReady?: boolean;
  /** Bağlanırken yalnızca çıktı dinle (MOTD); spawn etme */
  listenOnly?: boolean;
};

const RESIZE_DEBOUNCE_MS = 80;

export function XtermTerminal({
  sessionId,
  kind,
  hostId,
  active,
  focusOnActive = true,
  backendReady = false,
  listenOnly = false,
}: Props) {
  const { t } = useTranslation("terminal");
  const themeId = useThemeStore((s) => s.themeId);
  const terminalFontFamily = useSettingsStore((s) => s.terminalFontFamily);
  const terminalFontSize = useSettingsStore((s) => s.terminalFontSize);
  const terminalViewActive = useNavStore((s) => s.view === "terminal");
  const containerRef = useRef<HTMLDivElement>(null);
  const termRef = useRef<Terminal | null>(null);
  const fitRef = useRef<FitAddon | null>(null);
  const spawnedRef = useRef(false);
  const resizeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const scheduleFitAndResize = useCallback(() => {
    if (resizeTimerRef.current) {
      clearTimeout(resizeTimerRef.current);
    }
    resizeTimerRef.current = setTimeout(() => {
      resizeTimerRef.current = null;
      const term = termRef.current;
      const fit = fitRef.current;
      if (!term || !fit) return;
      fit.fit();
      if (spawnedRef.current) {
        terminalResize(sessionId, term.cols, term.rows);
      }
    }, RESIZE_DEBOUNCE_MS);
  }, [sessionId]);

  const focusTerminal = useCallback(() => {
    requestAnimationFrame(() => {
      termRef.current?.focus();
    });
  }, []);

  useEffect(() => {
    const term = termRef.current;
    if (!term) return;
    term.options.theme = getTheme(themeId).xterm;
  }, [themeId]);

  useEffect(() => {
    const term = termRef.current;
    const fit = fitRef.current;
    if (!term || !fit) return;
    term.options.fontFamily = buildFontFamilyCss(terminalFontFamily);
    term.options.fontSize = terminalFontSize;
    fit.fit();
    if (spawnedRef.current) {
      terminalResize(sessionId, term.cols, term.rows);
    }
  }, [terminalFontFamily, terminalFontSize]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const term = new Terminal({
      cursorBlink: true,
      fontSize: useSettingsStore.getState().terminalFontSize,
      fontFamily: buildFontFamilyCss(useSettingsStore.getState().terminalFontFamily),
      theme: getTheme(useThemeStore.getState().themeId).xterm,
      smoothScrollDuration: 0,
    });

    const fitAddon = new FitAddon();
    term.loadAddon(fitAddon);
    term.open(container);
    fitAddon.fit();

    termRef.current = term;
    fitRef.current = fitAddon;

    const dataDisposable = term.onData((data) => {
      if (kind === "ssh") {
        touchSessionActivity(sessionId);
      }
      terminalWrite(sessionId, data);
    });

    const startShell = async () => {
      if (spawnedRef.current || listenOnly) return;
      if (kind === "ssh" && backendReady) {
        spawnedRef.current = true;
        fitAddon.fit();
        terminalResize(sessionId, term.cols, term.rows);
        focusTerminal();
        return;
      }
      fitAddon.fit();
      const cols = term.cols;
      const rows = term.rows;
      try {
        if (kind === "ssh") {
          if (!hostId) {
            throw new Error(t("spawn.hostIdMissing"));
          }
          await spawnSshShell(sessionId, hostId, cols, rows);
        } else {
          await spawnLocalShell(sessionId, cols, rows);
        }
        spawnedRef.current = true;
        focusTerminal();
      } catch (err) {
        const label = kind === "ssh" ? t("spawn.sshFailed") : t("spawn.shellFailed");
        term.writeln(`\r\n\x1b[31m${label}:\x1b[0m ${formatAppError(err)}`);
      }
    };

    void startShell();

    const unsubStream = useTerminalStreamStore.getState().subscribe(sessionId, (base64) => {
      const bytes =
        kind === "ssh"
          ? translateTerminalChunk(base64, decodeTerminalData)
          : decodeTerminalData(base64);
      term.write(bytes);
    });

    const unlistenExit = listen<TerminalExitEvent>("terminal-exit", (event) => {
      if (event.payload.sessionId !== sessionId) return;
      term.writeln("\r\n\x1b[90m[oturum sona erdi]\x1b[0m");
      useSessionStore.getState().closeSession(sessionId);
    });

    const resizeObserver = new ResizeObserver(() => {
      scheduleFitAndResize();
    });
    resizeObserver.observe(container);

    const onPointerDown = () => {
      focusTerminal();
    };
    container.addEventListener("pointerdown", onPointerDown);

    return () => {
      if (resizeTimerRef.current) {
        clearTimeout(resizeTimerRef.current);
      }
      dataDisposable.dispose();
      resizeObserver.disconnect();
      container.removeEventListener("pointerdown", onPointerDown);
      unsubStream();
      void unlistenExit.then((fn) => fn());
      term.dispose();
      termRef.current = null;
      fitRef.current = null;
      spawnedRef.current = false;
    };
  }, [sessionId, kind, hostId, backendReady, listenOnly, scheduleFitAndResize, focusTerminal, t]);

  useEffect(() => {
    if (!listenOnly || spawnedRef.current) return;
    if (backendReady && fitRef.current && termRef.current) {
      spawnedRef.current = true;
      fitRef.current.fit();
      terminalResize(sessionId, termRef.current.cols, termRef.current.rows);
      focusTerminal();
    }
  }, [listenOnly, backendReady, sessionId, focusTerminal]);

  useEffect(() => {
    if (!focusOnActive) return;
    if (!active || !terminalViewActive || !fitRef.current || !termRef.current) return;
    const term = termRef.current;
    const fit = fitRef.current;
    fit.fit();
    if (spawnedRef.current) {
      terminalResize(sessionId, term.cols, term.rows);
    }
    focusTerminal();
  }, [active, focusOnActive, terminalViewActive, sessionId, focusTerminal]);

  return (
    <div
      className={`xterm-host ${active ? "xterm-host--active" : ""}`}
      ref={containerRef}
      aria-hidden={!active}
    />
  );
}
