// libs/ssh/src/key-drawer.component.ts
import { Component, effect, inject, input, output, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { TranslateModule } from "@ngx-translate/core";
import { TermshDrawerActionsComponent, TermshDrawerComponent } from "@termsh/angular";
import type { SshKey } from "@termsh/common";
import { KeyStateService } from "@termsh/state";
import { SecretInputComponent } from "@termsh/vault";

type AddMode = "import" | "generate";

function toTagList(tags: string): string[] {
  return tags
    .split(",")
    .map((tag) => tag.trim())
    .filter(Boolean)
    .slice(0, 20);
}

@Component({
  selector: "termsh-key-drawer",
  standalone: true,
  imports: [
    FormsModule,
    TranslateModule,
    TermshDrawerComponent,
    TermshDrawerActionsComponent,
    SecretInputComponent,
  ],
  template: `
    <termsh-drawer
      [open]="open()"
      variant="keys"
      [subtitle]="drawerSubtitle | translate"
      (close)="close.emit()"
    >
      <span drawerTitle>{{ drawerTitle | translate }}</span>

      @if (generatedPublicKey()) {
        <div drawerBody class="drawer__body mac-scrollbar">
          <div class="vault-field vault-field--snippet">
            <span>{{ 'keys.drawer.publicKeyLabel' | translate }}</span>
            <textarea [value]="generatedPublicKey()" readonly rows="4"></textarea>
          </div>
          @if (error()) {
            <p class="drawer-error">{{ error() }}</p>
          }
          <footer class="drawer__footer">
            <button type="button" class="btn btn--ghost" (click)="copyPublicKey()">
              {{ 'common.actions.copy' | translate }}
            </button>
            <button type="button" class="btn btn--primary" (click)="close.emit()">
              {{ 'keys.drawer.done' | translate }}
            </button>
          </footer>
        </div>
      } @else {
        <form drawerBody class="drawer__body mac-scrollbar" (ngSubmit)="submit()">
          @if (!keyItem()) {
            <div class="drawer__row" role="tablist" [attr.aria-label]="'keys.drawer.modeAria' | translate">
              <button
                type="button"
                role="tab"
                [attr.aria-selected]="addMode() === 'generate'"
                class="btn"
                [class.btn--primary]="addMode() === 'generate'"
                [class.btn--ghost]="addMode() !== 'generate'"
                (click)="addMode.set('generate')"
              >
                {{ 'keys.drawer.generate' | translate }}
              </button>
              <button
                type="button"
                role="tab"
                [attr.aria-selected]="addMode() === 'import'"
                class="btn"
                [class.btn--primary]="addMode() === 'import'"
                [class.btn--ghost]="addMode() !== 'import'"
                (click)="addMode.set('import')"
              >
                {{ 'keys.drawer.import' | translate }}
              </button>
            </div>
          }

          <div class="vault-field">
            <span>{{ 'keys.drawer.nameLabel' | translate }}</span>
            <input
              [(ngModel)]="name"
              name="name"
              required
              [placeholder]="'keys.drawer.namePlaceholder' | translate"
            />
          </div>

          <div class="vault-field">
            <span>{{ 'keys.drawer.tagsLabel' | translate }}</span>
            <input
              [(ngModel)]="tags"
              name="tags"
              [placeholder]="'keys.drawer.tagsPlaceholder' | translate"
            />
          </div>

          @if (!keyItem() && addMode() === 'generate') {
            <div class="vault-field">
              <span>{{ 'keys.drawer.algorithmLabel' | translate }}</span>
              <select [(ngModel)]="algorithm" name="algorithm">
                <option value="ed25519">{{ 'keys.drawer.algorithmEd25519' | translate }}</option>
                <option value="rsa">{{ 'keys.drawer.algorithmRsa' | translate }}</option>
              </select>
            </div>
          }

          @if ((!keyItem() && addMode() === 'import') || keyItem()) {
            <termsh-secret-input
              [label]="'keys.drawer.privateKeyLabel' | translate"
              name="privateKey"
              [(value)]="privateKey"
              [multiline]="true"
              [placeholder]="keyItem()
                ? ('keys.drawer.privateKeyPlaceholderRotate' | translate)
                : ('keys.drawer.privateKeyPlaceholderNew' | translate)"
            />
          }

          @if (error()) {
            <p class="drawer-error">{{ error() }}</p>
          }

          <termsh-drawer-actions
            [submitLabel]="submitLabel"
            [busy]="submitting()"
            [submitDisabled]="!name.trim()"
            (cancel)="close.emit()"
          />
        </form>
      }
    </termsh-drawer>
  `,
})
export class KeyDrawerComponent {
  readonly open = input(false);
  readonly keyItem = input<SshKey | null>(null);

  readonly close = output<void>();
  readonly saved = output<void>();

  private readonly keys = inject(KeyStateService);

  readonly addMode = signal<AddMode>("generate");
  readonly generatedPublicKey = signal<string | null>(null);
  readonly submitting = signal(false);
  readonly error = signal<string | null>(null);

  name = "";
  privateKey = "";
  algorithm: "ed25519" | "rsa" = "ed25519";
  tags = "";

  constructor() {
    effect(() => {
      if (!this.open()) return;
      const item = this.keyItem();
      this.addMode.set("generate");
      this.name = item?.name ?? "";
      this.privateKey = "";
      this.algorithm = "ed25519";
      this.tags = item?.tags.join(", ") ?? "";
      this.generatedPublicKey.set(null);
      this.submitting.set(false);
      this.error.set(null);
    });
  }

  get drawerTitle(): string {
    if (this.keyItem()) return "keys.drawer.titleEdit";
    if (this.generatedPublicKey()) return "keys.drawer.titleCreated";
    return "keys.drawer.titleAdd";
  }

  get drawerSubtitle(): string {
    return this.generatedPublicKey() ? "keys.drawer.subtitleCreated" : "keys.drawer.subtitleStored";
  }

  get submitLabel(): string {
    if (this.submitting()) {
      return this.keyItem() || this.addMode() === "import"
        ? "keys.drawer.saving"
        : "keys.drawer.generating";
    }
    if (this.keyItem()) return "common.actions.save";
    return this.addMode() === "generate" ? "keys.drawer.generate" : "common.actions.save";
  }

  async copyPublicKey() {
    const text = this.generatedPublicKey();
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      this.error.set("keys.drawer.errors.copyFailed");
    }
  }

  async submit() {
    this.error.set(null);

    if (!this.name.trim()) {
      this.error.set("keys.drawer.errors.nameRequired");
      return;
    }

    const item = this.keyItem();
    if (item) {
      this.submitting.set(true);
      try {
        await this.keys.save({
          id: item.id,
          name: this.name.trim(),
          privateKey: this.privateKey.trim(),
          tags: toTagList(this.tags),
        });
        this.saved.emit();
        this.close.emit();
      } catch (err) {
        this.error.set(err instanceof Error ? err.message : String(err));
      } finally {
        this.submitting.set(false);
      }
      return;
    }

    if (this.addMode() === "generate") {
      this.submitting.set(true);
      try {
        const result = await this.keys.generate({
          name: this.name.trim(),
          algorithm: this.algorithm,
          tags: toTagList(this.tags),
        });
        this.generatedPublicKey.set(result.publicKeyPem);
        this.saved.emit();
      } catch (err) {
        this.error.set(err instanceof Error ? err.message : String(err));
      } finally {
        this.submitting.set(false);
      }
      return;
    }

    if (!this.privateKey.trim()) {
      this.error.set("keys.drawer.errors.privateKeyRequired");
      return;
    }

    this.submitting.set(true);
    try {
      await this.keys.save({
        name: this.name.trim(),
        privateKey: this.privateKey.trim(),
        tags: toTagList(this.tags),
      });
      this.saved.emit();
      this.close.emit();
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : String(err));
    } finally {
      this.submitting.set(false);
    }
  }
}

// apps/desktop-legacy/src/components/keys/KeyDrawer.tsx
import { FormEvent, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import type { SshKey } from "@termsh/shared";
import { formatAppError } from "@/lib/errors/appError";
import type { GenerateKeyResult } from "@/lib/keys/ipc";
import { Icon } from "@/components/ui/Icon";

type AddMode = "import" | "generate";

type Props = {
  open: boolean;
  keyItem?: SshKey | null;
  onClose: () => void;
  onSave: (payload: { id?: string; name: string; privateKeyPem?: string; tags: string[] }) => Promise<unknown>;
  onGenerate?: (payload: {
    name: string;
    algorithm: "ed25519" | "rsa";
    tags: string[];
  }) => Promise<GenerateKeyResult>;
};

function toTagList(tags: string): string[] {
  return tags
    .split(",")
    .map((tag) => tag.trim())
    .filter(Boolean)
    .slice(0, 20);
}

export function KeyDrawer({ open, keyItem, onClose, onSave, onGenerate }: Props) {
  const { t } = useTranslation(["keys", "common"]);
  const [addMode, setAddMode] = useState<AddMode>("generate");
  const [name, setName] = useState("");
  const [privateKeyPem, setPrivateKeyPem] = useState("");
  const [algorithm, setAlgorithm] = useState<"ed25519" | "rsa">("ed25519");
  const [tags, setTags] = useState("");
  const [generatedPublicKey, setGeneratedPublicKey] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;
    setAddMode("generate");
    setName(keyItem?.name ?? "");
    setPrivateKeyPem("");
    setAlgorithm("ed25519");
    setTags(keyItem?.tags.join(", ") ?? "");
    setGeneratedPublicKey(null);
    setSubmitting(false);
    setError(null);
  }, [open, keyItem]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  const copyPublicKey = async () => {
    if (!generatedPublicKey) return;
    try {
      await navigator.clipboard.writeText(generatedPublicKey);
    } catch {
      setError(t("drawer.errors.copyFailed"));
    }
  };

  const onSubmit = async (event: FormEvent) => {
    event.preventDefault();
    setError(null);

    if (!name.trim()) {
      setError(t("drawer.errors.nameRequired"));
      return;
    }

    if (keyItem) {
      setSubmitting(true);
      try {
        await onSave({
          id: keyItem.id,
          name: name.trim(),
          privateKeyPem: privateKeyPem.trim() ? privateKeyPem.trim() : undefined,
          tags: toTagList(tags),
        });
        onClose();
      } catch (err) {
        setError(formatAppError(err));
      } finally {
        setSubmitting(false);
      }
      return;
    }

    if (addMode === "generate") {
      if (!onGenerate) {
        setError(t("drawer.errors.generateUnavailable"));
        return;
      }
      setSubmitting(true);
      try {
        const result = await onGenerate({
          name: name.trim(),
          algorithm,
          tags: toTagList(tags),
        });
        setGeneratedPublicKey(result.publicKeyPem);
      } catch (err) {
        setError(formatAppError(err));
      } finally {
        setSubmitting(false);
      }
      return;
    }

    if (!privateKeyPem.trim()) {
      setError(t("drawer.errors.privateKeyRequired"));
      return;
    }

    setSubmitting(true);
    try {
      await onSave({
        name: name.trim(),
        privateKeyPem: privateKeyPem.trim(),
        tags: toTagList(tags),
      });
      onClose();
    } catch (err) {
      setError(formatAppError(err));
    } finally {
      setSubmitting(false);
    }
  };

  const title = keyItem
    ? t("drawer.titleEdit")
    : generatedPublicKey
      ? t("drawer.titleCreated")
      : t("drawer.titleAdd");

  return (
    <div className={`drawer-root ${open ? "drawer-root--open" : ""}`} aria-hidden={!open}>
      <button
        type="button"
        className="drawer-root__backdrop"
        aria-label={t("common:actions.close")}
        tabIndex={open ? 0 : -1}
        onClick={onClose}
      />
      <aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="key-drawer-title" aria-hidden={!open}>
        <header className="drawer__header">
          <div>
            <h2 id="key-drawer-title">{title}</h2>
            <p className="drawer__sub">
              {generatedPublicKey ? t("drawer.subtitleCreated") : t("drawer.subtitleStored")}
            </p>
          </div>
          <button type="button" className="drawer__close" onClick={onClose} aria-label={t("common:actions.close")}>
            <Icon name="close" size={20} />
          </button>
        </header>

        {generatedPublicKey ? (
          <div className="drawer__body mac-scrollbar">
            <label className="vault-field">
              <span>{t("drawer.publicKeyLabel")}</span>
              <textarea value={generatedPublicKey} readOnly rows={4} />
            </label>
            {error && <p className="drawer-error">{error}</p>}
            <footer className="drawer__footer">
              <button type="button" className="btn btn--ghost" onClick={() => void copyPublicKey()}>
                {t("common:actions.copy")}
              </button>
              <button type="button" className="btn btn--primary" onClick={onClose}>
                {t("drawer.done")}
              </button>
            </footer>
          </div>
        ) : (
          <form className="drawer__body mac-scrollbar" onSubmit={onSubmit} autoComplete="off">
            {!keyItem && (
              <div className="drawer__row" role="tablist" aria-label={t("drawer.modeAria")}>
                <button
                  type="button"
                  role="tab"
                  aria-selected={addMode === "generate"}
                  className={`btn ${addMode === "generate" ? "btn--primary" : "btn--ghost"}`}
                  onClick={() => setAddMode("generate")}
                >
                  {t("drawer.generate")}
                </button>
                <button
                  type="button"
                  role="tab"
                  aria-selected={addMode === "import"}
                  className={`btn ${addMode === "import" ? "btn--primary" : "btn--ghost"}`}
                  onClick={() => setAddMode("import")}
                >
                  {t("drawer.import")}
                </button>
              </div>
            )}

            <label className="vault-field">
              <span>{t("drawer.nameLabel")}</span>
              <input value={name} onChange={(e) => setName(e.target.value)} placeholder={t("drawer.namePlaceholder")} />
            </label>

            <label className="vault-field">
              <span>{t("drawer.tagsLabel")}</span>
              <input value={tags} onChange={(e) => setTags(e.target.value)} placeholder={t("drawer.tagsPlaceholder")} />
            </label>

            {!keyItem && addMode === "generate" && (
              <label className="vault-field">
                <span>{t("drawer.algorithmLabel")}</span>
                <select value={algorithm} onChange={(e) => setAlgorithm(e.target.value as "ed25519" | "rsa")}>
                  <option value="ed25519">{t("drawer.algorithmEd25519")}</option>
                  <option value="rsa">{t("drawer.algorithmRsa")}</option>
                </select>
              </label>
            )}

            {(!keyItem && addMode === "import") || keyItem ? (
              <label className="vault-field">
                <span>{t("drawer.privateKeyLabel")}</span>
                <textarea
                  value={privateKeyPem}
                  onChange={(e) => setPrivateKeyPem(e.target.value)}
                  placeholder={
                    keyItem ? t("drawer.privateKeyPlaceholderRotate") : t("drawer.privateKeyPlaceholderNew")
                  }
                  rows={10}
                />
              </label>
            ) : null}

            {error && <p className="drawer-error">{error}</p>}

            <footer className="drawer__footer">
              <button type="button" className="btn btn--ghost" onClick={onClose} disabled={submitting}>
                {t("common:actions.cancel")}
              </button>
              <button type="submit" className="btn btn--primary" disabled={submitting || !name.trim()}>
                {submitting
                  ? keyItem || addMode === "import"
                    ? t("drawer.saving")
                    : t("drawer.generating")
                  : keyItem
                    ? t("common:actions.save")
                    : addMode === "generate"
                      ? t("drawer.generate")
                      : t("common:actions.save")}
              </button>
            </footer>
          </form>
        )}
      </aside>
    </div>
  );
}
