// apps/desktop-legacy/src/components/views/KeysView.tsx
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import type { SshKey } from "@termsh/shared";
import { KeyDrawer } from "@/components/keys/KeyDrawer";
import { DrawerPortal } from "@/components/ui/DrawerPortal";
import { useKeyStore } from "@/stores/keyStore";
import { useVaultStore } from "@/stores/vaultStore";

export function KeysView() {
  const { t } = useTranslation(["keys", "common"]);
  const load = useKeyStore((s) => s.load);
  const keys = useKeyStore((s) => s.keys);
  const loading = useKeyStore((s) => s.loading);
  const error = useKeyStore((s) => s.error);
  const save = useKeyStore((s) => s.save);
  const generate = useKeyStore((s) => s.generate);
  const remove = useKeyStore((s) => s.remove);

  const vaultStatus = useVaultStore((s) => s.status);
  const vaultReady = Boolean(vaultStatus?.isSetup && vaultStatus?.isUnlocked);

  const [query, setQuery] = useState("");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [editing, setEditing] = useState<SshKey | null>(null);

  useEffect(() => {
    void load();
  }, [load]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return keys;
    return keys.filter((k) => `${k.name}\n${k.tags.join(",")}`.toLowerCase().includes(q));
  }, [keys, query]);

  const onAdd = () => {
    setEditing(null);
    setDrawerOpen(true);
  };

  const onEdit = (k: SshKey) => {
    setEditing(k);
    setDrawerOpen(true);
  };

  const onDelete = async (id: string) => {
    // eslint-disable-next-line no-alert
    if (!confirm(t("deleteConfirm"))) return;
    await remove(id);
  };

  return (
    <div className="view">
      <header className="view__head view__head--row">
        <div>
          <h1>{t("title")}</h1>
          <p className="view__sub">{t("subtitle")}</p>
        </div>
        <div className="view__head-actions">
          <button type="button" className="btn btn--primary" onClick={onAdd} disabled={!vaultReady}>
            {t("addKey")}
          </button>
        </div>
      </header>

      <div className="view__scroll mac-scrollbar">
        {!vaultReady && <p className="view__empty">{t("vaultLocked")}</p>}

        {error && <p className="view__empty">{error}</p>}

        <input
          className="snippets-search"
          placeholder={t("searchPlaceholder")}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />

        {loading && <p className="view__empty">{t("snippets:loading")}</p>}
        {!loading && filtered.length === 0 && <p className="view__empty">{t("empty")}</p>}

        <ul className="snippets-list">
          {filtered.map((k) => (
            <li key={k.id} className="snippets-row">
              <button type="button" className="snippets-row__main" onClick={() => onEdit(k)} disabled={!vaultReady}>
                <div className="snippets-row__title">{k.name}</div>
                <div className="snippets-row__meta">
                  {k.tags.length > 0 ? k.tags.join(" · ") : t("snippets:noTags")}
                </div>
              </button>
              <div className="snippets-row__actions">
                <button type="button" className="btn btn--ghost" onClick={() => onEdit(k)} disabled={!vaultReady}>
                  {t("common:actions.edit")}
                </button>
                <button type="button" className="btn btn--ghost" onClick={() => void onDelete(k.id)} disabled={!vaultReady}>
                  {t("common:actions.delete")}
                </button>
              </div>
            </li>
          ))}
        </ul>
      </div>

      <DrawerPortal>
        <KeyDrawer
          open={drawerOpen}
          keyItem={editing}
          onClose={() => setDrawerOpen(false)}
          onSave={(payload) => save(payload)}
          onGenerate={(payload) => generate(payload)}
        />
      </DrawerPortal>
    </div>
  );
}

// libs/ssh/src/keys-view.component.ts
import { AsyncPipe } from "@angular/common";
import { Component, inject, OnInit, signal } from "@angular/core";
import { TranslateModule } from "@ngx-translate/core";
import type { SshKey } from "@termsh/common";
import { KeyStateService, VaultStateService } from "@termsh/state";
import { KeyDrawerComponent } from "./key-drawer.component";

@Component({
  selector: "termsh-keys-view",
  standalone: true,
  imports: [AsyncPipe, TranslateModule, KeyDrawerComponent],
  template: `
    <div class="view">
      <header class="view__head view__head--row">
        <div>
          <h1>{{ 'keys.title' | translate }}</h1>
          <p class="view__sub">{{ 'keys.subtitle' | translate }}</p>
        </div>
        <button type="button" class="btn btn--primary" [disabled]="!vaultReady" (click)="openNew()">
          {{ 'keys.addKey' | translate }}
        </button>
      </header>
      <div class="view__scroll mac-scrollbar">
        @if (!vaultReady) {
          <p class="view__empty">{{ 'keys.vaultLocked' | translate }}</p>
        } @else if (state.loading$stream | async) {
          <p class="view__empty">{{ 'snippets.loading' | translate }}</p>
        } @else if ((state.keysStream$ | async)?.length === 0) {
          <p class="view__empty">{{ 'keys.empty' | translate }}</p>
        } @else {
          <ul class="snippets-list">
            @for (k of state.keysStream$ | async; track k.id) {
              <li class="snippet-row">
                <div class="snippet-row__main">
                  <span class="snippet-row__title">{{ k.name }}</span>
                  @if (k.tags.length) {
                    <span class="snippet-row__preview">{{ k.tags.join(', ') }}</span>
                  }
                </div>
                <button type="button" class="snippet-row__edit" (click)="openEdit(k)">
                  {{ 'common.actions.edit' | translate }}
                </button>
                <button type="button" class="snippet-row__edit" (click)="remove(k)">
                  {{ 'common.actions.delete' | translate }}
                </button>
              </li>
            }
          </ul>
        }
      </div>

      <termsh-key-drawer
        [open]="drawerOpen()"
        [keyItem]="editingKey()"
        (close)="closeDrawer()"
        (saved)="onSaved()"
      />
    </div>
  `,
})
export class KeysViewComponent implements OnInit {
  readonly state = inject(KeyStateService);
  private readonly vault = inject(VaultStateService);

  readonly drawerOpen = signal(false);
  readonly editingKey = signal<SshKey | null>(null);

  ngOnInit() {
    void this.state.load();
  }

  get vaultReady(): boolean {
    const s = this.vault.status;
    return Boolean(s?.isSetup && s.isUnlocked);
  }

  openNew() {
    this.editingKey.set(null);
    this.drawerOpen.set(true);
  }

  openEdit(k: SshKey) {
    this.editingKey.set(k);
    this.drawerOpen.set(true);
  }

  closeDrawer() {
    this.drawerOpen.set(false);
    this.editingKey.set(null);
  }

  onSaved() {
    void this.state.load();
  }

  async remove(k: SshKey) {
    await this.state.remove(k.id);
  }
}
